version: '3.7'
services:
  app:
    image: playground-micronaut:1.0.0
    container_name: playground
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://db/playground
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: postgres:10.5-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=playground
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
