version: '3.7'
services:
  clients:
    image: pg-clients-backend:1.0.0
    container_name: clients-backend
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://db-clients/playground
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KAFKA_HOST=kafka:29092
    ports:
      - "8081:8080"
    depends_on:
      - "db-clients"
      - "kafka"
  sessions:
    image: pg-sessions-backend:1.0.0
    container_name: sessions-backend
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://db-sessions/playground
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KAFKA_HOST=kafka:29092
    ports:
      - "8082:8080"
    depends_on:
      - "db-sessions"
      - "kafka"
  db-clients:
    image: postgres:10.5-alpine
    container_name: clients-db
    restart: always
    environment:
      - POSTGRES_DB=playground
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '32001:5432'
    volumes:
      - ./db/clients-data:/var/lib/postgresql/data
  db-sessions:
    image: postgres:10.5-alpine
    container_name: sessions-db
    restart: always
    environment:
      - POSTGRES_DB=playground
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '32002:5432'
    volumes:
      - ./db/sessions-data:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1