micronaut:
  application:
    name: playground-events-backend
endpoints:
  health:
    details-visible: ANONYMOUS
kafka:
  bootstrap:
    servers: ${KAFKA_HOST:`localhost:9092`}
jackson:
  serialization:
