apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clients-db
spec:
  replicas: 1
  serviceName: clients-db-service
  selector:
    matchLabels:
      app: clients-db
  template:
    metadata:
      labels:
        app: clients-db
    spec:
      containers:
      - name: clients-db
        image: postgres:10.5-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: clients-db-configmap
        volumeMounts:
        - name: clients-db
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres", "-d", "clients", "-q"]
          initialDelaySeconds: 15
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command: ["psql", "-U", "postgres", "-d", "clients", "-c", "SELECT 1"]
          initialDelaySeconds: 45
          timeoutSeconds: 2
      volumes:
      - name: clients-db
        persistentVolumeClaim:
          claimName: clients-db-pv-claim
