micronaut:
  application:
    name: playground-clients-backend
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost/playground`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:`postgres`}
    password: ${DB_PASSWORD:`postgres`}
    schema-generate: NONE
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
jackson:
  serialization:
    writeDatesAsTimestamps: false